table inventory_data
	lineageTag: 981b88e9-5d1a-4597-b76d-714361cf60d2

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0999e8be-ee52-40cd-b578-4cc2c1fa5064
		summarizeBy: none
		sourceColumn: Date

		variation Variación
			isDefault
			relationship: 7834d8a5-46ab-40d1-8680-a387c60f3265
			defaultHierarchy: LocalDateTable_3fa1e710-1047-4487-a8b3-46df4e69dac8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Item_ID
		dataType: int64
		formatString: 0
		lineageTag: cfae20be-418e-42f5-9ab2-2fcee24399ae
		summarizeBy: count
		sourceColumn: Item_ID

		annotation SummarizationSetBy = Automatic

	column Item_Type
		dataType: string
		lineageTag: ad2606f7-f285-4464-b503-5532fae7e8bc
		summarizeBy: none
		sourceColumn: Item_Type

		annotation SummarizationSetBy = Automatic

	column Item_Name
		dataType: string
		lineageTag: 535d8057-caf1-4432-a989-ba44824f1fe7
		summarizeBy: none
		sourceColumn: Item_Name

		annotation SummarizationSetBy = Automatic

	column Current_Stock
		dataType: int64
		formatString: 0
		lineageTag: dad19ef4-1caf-463c-a5e8-c61f6cc64f35
		summarizeBy: sum
		sourceColumn: Current_Stock

		annotation SummarizationSetBy = Automatic

	column Min_Required
		dataType: int64
		formatString: 0
		lineageTag: 1500b920-51d9-46bf-b316-ee3bd80c5a27
		summarizeBy: sum
		sourceColumn: Min_Required

		annotation SummarizationSetBy = Automatic

	column Max_Capacity
		dataType: int64
		formatString: 0
		lineageTag: fd2fcafa-0e9c-4960-9108-e07068f1f0e7
		summarizeBy: sum
		sourceColumn: Max_Capacity

		annotation SummarizationSetBy = Automatic

	column Unit_Cost
		dataType: double
		lineageTag: e325ac96-7e8f-4e09-b3aa-74f4f4a86910
		summarizeBy: sum
		sourceColumn: Unit_Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Avg_Usage_Per_Day
		dataType: int64
		formatString: 0
		lineageTag: f1974f80-bdf2-4508-aefc-0ebe3703c4fa
		summarizeBy: sum
		sourceColumn: Avg_Usage_Per_Day

		annotation SummarizationSetBy = Automatic

	column Restock_Lead_Time
		dataType: int64
		formatString: 0
		lineageTag: a54ccc7b-c3de-4ec5-8824-b78be3a6ab06
		summarizeBy: sum
		sourceColumn: Restock_Lead_Time

		annotation SummarizationSetBy = Automatic

	column Vendor_ID
		dataType: string
		lineageTag: 44c5418f-e6ef-403e-ac3b-994cdf31048e
		summarizeBy: none
		sourceColumn: Vendor_ID

		annotation SummarizationSetBy = Automatic

	column 'Total min required inventory amount' = ```
			SUMX(inventory_data, inventory_data[Min_Required] * inventory_data[Unit_Cost]) 
			```
		lineageTag: 7271150e-b348-48f8-8f36-6339327b3c03
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition inventory_data = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Edwin\Downloads\BI\Bi_proyecto\Base Proyecto\inventory_data.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Date", type date}, {"Item_ID", Int64.Type}, {"Item_Type", type text}, {"Item_Name", type text}, {"Current_Stock", Int64.Type}, {"Min_Required", Int64.Type}, {"Max_Capacity", Int64.Type}, {"Unit_Cost", type number}, {"Avg_Usage_Per_Day", Int64.Type}, {"Restock_Lead_Time", Int64.Type}, {"Vendor_ID", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

