table healthcare_dataset
	lineageTag: 64291985-e0d1-43ec-81bf-bd46e531dd34

	column Patient_ID
		dataType: string
		lineageTag: 74b43f46-b863-4d1a-a524-5ec4723e8982
		summarizeBy: none
		sourceColumn: Patient_ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: f6eadb9e-d8ef-4707-819c-274fd09df730
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: e174d882-dc82-42da-b072-4c47de4aba54
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: d977c110-be76-41d4-ab83-878488032ae6
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'Blood Type'
		dataType: string
		lineageTag: 074b5efc-161f-405e-a4f4-ed7aa4afa933
		summarizeBy: none
		sourceColumn: Blood Type

		annotation SummarizationSetBy = Automatic

	column 'Medical Condition'
		dataType: string
		lineageTag: eb48e4f9-2035-41f1-b6af-36838f51e886
		summarizeBy: none
		sourceColumn: Medical Condition

		annotation SummarizationSetBy = Automatic

	column 'Admission Type'
		dataType: string
		lineageTag: bc4b73f1-d14e-4072-b279-2130f30806bd
		summarizeBy: none
		sourceColumn: Admission Type

		annotation SummarizationSetBy = Automatic

	column Medication
		dataType: string
		lineageTag: 2240c984-f904-4223-8c12-62ac69d8bb38
		summarizeBy: none
		sourceColumn: Medication

		annotation SummarizationSetBy = Automatic

	column 'Test Results'
		dataType: string
		lineageTag: 59c0c4a6-1372-4d22-9a32-cef013b5af1a
		summarizeBy: none
		sourceColumn: Test Results

		annotation SummarizationSetBy = Automatic

	partition healthcare_dataset = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Edwin\Downloads\BI\Bi_proyecto\Base Proyecto\healthcare_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Patient_ID", type text}, {"Name", type text}, {"Age", Int64.Type}, {"Gender", type text}, {"Blood Type", type text}, {"Medical Condition", type text}, {"Admission Type", type text}, {"Medication", type text}, {"Test Results", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

