table HorasExtra
	lineageTag: 8c675680-1ebf-4b7d-9c0e-1f7fd551dfd4

	column ID_Empleado
		dataType: string
		lineageTag: 26889308-5fe7-4e58-aa7b-1e8ad6d83a8b
		summarizeBy: none
		sourceColumn: ID_Empleado

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: d0d53017-5b00-4278-ac32-aa4358186463
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: b8c7fabe-178b-4814-a3a9-bcdb6ebb21e7
			defaultHierarchy: LocalDateTable_613515bf-f970-41d0-9401-c7e3ac61c45d.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Horas_Extra
		dataType: int64
		formatString: 0
		lineageTag: 7d06ba8d-a4c9-42b6-89a4-1d08014a16cd
		summarizeBy: sum
		sourceColumn: Horas_Extra

		annotation SummarizationSetBy = Automatic

	partition HorasExtra = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Downloads\HR_Dataset_Extendido.xlsx"), null, true),
				    HorasExtra_Sheet = Source{[Item="HorasExtra",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(HorasExtra_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Empleado", type text}, {"Fecha", Int64.Type}, {"Horas_Extra", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

