table Asistencias
	lineageTag: b00d4c2f-d6b4-4180-9773-085836761111

	column ID_Empleado
		dataType: string
		lineageTag: 3b2a2439-818b-4ac2-a29a-d024bdefe7cb
		summarizeBy: none
		sourceColumn: ID_Empleado

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9305f609-d9fb-401e-b88d-ff5971683704
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: f375d666-58ee-45d1-a35f-26d6b679af30
			defaultHierarchy: LocalDateTable_efa360d1-2b6b-4843-8940-4ad504c91432.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Asistencia
		dataType: string
		lineageTag: 2c19743f-e8cc-4cab-bd6b-01d12cd805b8
		summarizeBy: none
		sourceColumn: Asistencia

		annotation SummarizationSetBy = Automatic

	column TipoAusencia
		dataType: string
		lineageTag: f2c80e91-3788-4f92-a19e-10765f04386d
		summarizeBy: none
		sourceColumn: TipoAusencia

		annotation SummarizationSetBy = Automatic

	partition Asistencias = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Downloads\HR_Dataset_Extendido.xlsx"), null, true),
				    Asistencias_Sheet = Source{[Item="Asistencias",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Asistencias_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Empleado", type text}, {"Fecha", Int64.Type}, {"Asistencia", type text}, {"TipoAusencia", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

