table Bajas
	lineageTag: dfc1e93c-0024-452f-8072-b2bbf65f8bbd

	column ID_Empleado
		dataType: string
		lineageTag: f2574980-20f3-4dc9-abb9-b76048ac70e0
		summarizeBy: none
		sourceColumn: ID_Empleado

		annotation SummarizationSetBy = Automatic

	column Fecha_Baja
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7f7fddd9-1b13-4074-8442-c877dd286cc1
		summarizeBy: none
		sourceColumn: Fecha_Baja

		variation Variation
			isDefault
			relationship: 8ef50f24-20c7-466c-ba24-d52db0a195bf
			defaultHierarchy: LocalDateTable_81ea85f9-db78-43d6-b2d0-25d63257fa6d.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Motivo_Baja
		dataType: string
		lineageTag: 9f415405-7b15-4f7f-a37b-f595541c4bd1
		summarizeBy: none
		sourceColumn: Motivo_Baja

		annotation SummarizationSetBy = Automatic

	partition Bajas = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Downloads\HR_Dataset_Extendido.xlsx"), null, true),
				    Bajas_Sheet = Source{[Item="Bajas",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Bajas_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Empleado", type text}, {"Fecha_Baja", Int64.Type}, {"Motivo_Baja", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

